name: clas12 environment modules CI
on:
  push:
    branches: [ ci ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test0
        run: echo Hello from the Organization
      - name: test1
        run: apt-get install environment-modules
